In [3]:
import torch
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline

## intro to tensor

In [5]:
#scalar
scalar=torch.tensor(7)
scalar

tensor(7)

In [6]:
scalar.ndim

0

In [9]:
# Get tensor back as python int
scalar.item()

7

In [10]:
#vector
vector=torch.tensor([7,7])
vector

tensor([7, 7])

In [18]:
vector.ndim

1

In [20]:
vector.shape


torch.Size([2])

In [28]:
x=np.array([[1,5],[5,4]])
x.shape
x.ndim

2

In [29]:
#MATRIX
MATRIX=torch.tensor([[7,8],[9,10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [31]:
MATRIX[0]

tensor([7, 8])

In [32]:
MATRIX.ndim

2

In [33]:
MATRIX.shape

torch.Size([2, 2])

In [45]:
#TENSOR
TENSOR=torch.tensor([  [[1,2,3],[4,5,6],[7,8,9]]  ,  [[13,14,15],[16,17,18],[10,11,12]]  ])
#this is a matrix torch.tensor([[1,2,3],[4,5,6],[7,8,9]])
TENSOR

tensor([[[ 1,  2,  3],
         [ 4,  5,  6],
         [ 7,  8,  9]],

        [[13, 14, 15],
         [16, 17, 18],
         [10, 11, 12]]])

In [42]:
TENSOR.shape

torch.Size([1, 3, 3])

In [43]:
TENSOR.ndim

3

In [49]:
TENSOR[1,2,0]

tensor(10)

## Random Tensor

why random tensor are important?
because the way many neural networks learn is that they start with tensors full of random number
and then adjust those random numbers to better represent the data

In [53]:
# Create a random tensors of size(3,4)
random_tensor=torch.rand(3,4)
random_tensor

tensor([[0.1660, 0.6330, 0.3093, 0.9610],
        [0.4786, 0.7743, 0.1169, 0.5238],
        [0.6114, 0.4008, 0.2302, 0.8427]])

In [54]:
random_tensor.ndim

2

In [56]:
#create a random temsor with similar shape  to an image tensor
random_image_size_tensor=torch.rand(224,224,3)
random_image_size_tensor

tensor([[[0.5141, 0.3051, 0.8246],
         [0.4247, 0.5082, 0.8084],
         [0.8562, 0.0373, 0.0539],
         ...,
         [0.0681, 0.3057, 0.6089],
         [0.6552, 0.3517, 0.8321],
         [0.2161, 0.3479, 0.3429]],

        [[0.3197, 0.2018, 0.1695],
         [0.9089, 0.4798, 0.6286],
         [0.3301, 0.8955, 0.4485],
         ...,
         [0.0582, 0.3763, 0.3514],
         [0.6952, 0.1811, 0.9296],
         [0.4257, 0.6533, 0.1353]],

        [[0.3216, 0.5040, 0.5293],
         [0.4794, 0.1463, 0.1049],
         [0.2939, 0.3138, 0.3376],
         ...,
         [0.9867, 0.3931, 0.7344],
         [0.0514, 0.9799, 0.7740],
         [0.5872, 0.8952, 0.6597]],

        ...,

        [[0.9909, 0.4084, 0.9920],
         [0.8271, 0.4419, 0.7393],
         [0.3186, 0.3334, 0.5563],
         ...,
         [0.4628, 0.6863, 0.1485],
         [0.6125, 0.0953, 0.1550],
         [0.8768, 0.0839, 0.8765]],

        [[0.6128, 0.6395, 0.5456],
         [0.0520, 0.2991, 0.0879],
         [0.

## Zeros and Ones

In [61]:
#Create a tensor of all zeros
zeros=torch.zeros(3,4)
zeros
ones=torch.ones(3,4)
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [62]:
ones.dtype

torch.float32

## Creating a range of tesors and tesnsors like

In [68]:
# use torch.range
x=torch.arange(start=1,end=11)
x

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [69]:
ten_zeros=torch.zeros_like(input=x)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

## Tensor DataType

In [89]:
#float 32 tensor
float_32_tensor= torch.tensor([3.0,6,9],dtype=float,device=None,requires_grad=False)

In [91]:
print(float_32_tensor.device)
print(float_32_tensor.dtype)

cpu
torch.float64


In [92]:
float_16_tensor=float_32_tensor.type(torch.float16)

In [93]:
float_16_tensor.dtype

torch.float16

In [105]:
x=torch.tensor(data=2,dtype=torch.float64)

In [106]:
x.itemsize

8

## Tensor Operation

In [107]:
#Mainpulating tensor (tensor operation)

In [108]:
tensor=torch.tensor([1,2,3])
tensor

tensor([1, 2, 3])

In [111]:
print(tensor*10)
print(tensor+10)
print(tensor-10)
print(tensor**10)

tensor([10, 20, 30])
tensor([11, 12, 13])
tensor([-9, -8, -7])
tensor([    1,  1024, 59049])


In [6]:
%%time
MatA=torch.tensor([[1,2],[3,4]])
MatB=torch.tensor([[1,0],[0,1]])
torch.matmul(MatA,MatB)

CPU times: total: 0 ns
Wall time: 458 μs


tensor([[1, 2],
        [3, 4]])

## one of the most common errors in deep learning:Shape Errors

In [8]:
mat_a=torch.tensor([[1,2],[3,4],[5,6]])
mat_b=torch.tensor([[3,1],[6,1],[9,8]])
torch.matmul(mat_a,mat_b.T)

tensor([[ 5,  8, 25],
        [13, 22, 59],
        [21, 36, 93]])

## Finding min,max,mean,sum,etc(tensor aggregation)

In [11]:
x=torch.arange(0,100,10)

In [32]:
torch.min(x),x.min()

(tensor(0), tensor(0))

In [33]:
torch.max(x),x.max

(tensor(90), <function Tensor.max>)

In [36]:
torch.mean(x)

RuntimeError: mean(): could not infer output dtype. Input dtype must be either a floating point or complex dtype. Got: Long

In [38]:
torch.mean(x.type(torch.float32)),x.type(torch.float32).mean()

(tensor(45.), tensor(45.))

In [39]:
torch.sum(x),x.sum()

(tensor(450), tensor(450))

In [43]:
torch.argmax(x),x.argmax()##show us the position of the minimum element

(tensor(9), tensor(9))

## Reashaping,stacking tensors

In [78]:
x=torch.arange(1,10)
x

tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [116]:
x_reshaped=x.reshape([1,9])
x_reshaped

tensor([[1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [80]:
x_review=x.view([3,3])
x_review

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [81]:
## Search for the diffrence between view and reshape

In [106]:
#Stacking: combine multiple tensors on top of each other (vstack) or side by side(hstack)
x_stack=torch.stack([x,x,x,x,x,x,x,x,x],dim=0)

print(f'{x}\n')
x_stack

tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])



tensor([[1, 2, 3, 4, 5, 6, 7, 8, 9],
        [1, 2, 3, 4, 5, 6, 7, 8, 9],
        [1, 2, 3, 4, 5, 6, 7, 8, 9],
        [1, 2, 3, 4, 5, 6, 7, 8, 9],
        [1, 2, 3, 4, 5, 6, 7, 8, 9],
        [1, 2, 3, 4, 5, 6, 7, 8, 9],
        [1, 2, 3, 4, 5, 6, 7, 8, 9],
        [1, 2, 3, 4, 5, 6, 7, 8, 9],
        [1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [103]:
x_stack=torch.stack([x,x,x,x,x,x,x,x,x],dim=1)
print(f'{x}\n')
x_stack

tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])



tensor([[1, 1, 1, 1, 1, 1, 1, 1, 1],
        [2, 2, 2, 2, 2, 2, 2, 2, 2],
        [3, 3, 3, 3, 3, 3, 3, 3, 3],
        [4, 4, 4, 4, 4, 4, 4, 4, 4],
        [5, 5, 5, 5, 5, 5, 5, 5, 5],
        [6, 6, 6, 6, 6, 6, 6, 6, 6],
        [7, 7, 7, 7, 7, 7, 7, 7, 7],
        [8, 8, 8, 8, 8, 8, 8, 8, 8],
        [9, 9, 9, 9, 9, 9, 9, 9, 9]])

## squeezing,unsqueezing tensors

In [125]:
# squeezing : remove all single dimensions from a target tensor
print(f'x_reshaped shape is :{x_reshaped.shape}')
x_squeezed=torch.squeeze(x_reshaped)
print(f'squeezing x_reshaped result shape is:{x_squeezed.shape}')
x_unsqueezed=torch.unsqueeze(x_squeezed,dim=0)
print(f'unsqueezing x_squeezed in dim=0 result shape is:{x_unsqueezed.shape}')
x_unsqueezed=torch.unsqueeze(x_squeezed,dim=1)
print(f'unsqueezing x_squeezed in dim=1 result shape is:{x_unsqueezed.shape}')



x_reshaped shape is :torch.Size([1, 9])
squeezing x_reshaped result shape is:torch.Size([9])
unsqueezing x_squeezed in dim=0 result shape is:torch.Size([1, 9])
unsqueezing x_squeezed in dim=1 result shape is:torch.Size([9, 1])


## torch.permute:
rearranges the dimensions of a target tensor in special orders

In [131]:
x_original=torch.rand(size=(224,224,3))#height,width ,color_channels
x_permuted=x_original.permute(2,0,1)
print(x_original.shape)
print(x_permuted.shape)

torch.Size([224, 224, 3])
torch.Size([3, 224, 224])


In [133]:
x_permuted

tensor([[[0.2276, 0.9851, 0.4837,  ..., 0.8674, 0.0050, 0.7194],
         [0.7118, 0.3960, 0.4611,  ..., 0.5893, 0.4343, 0.4934],
         [0.3041, 0.9188, 0.3805,  ..., 0.6653, 0.6897, 0.8569],
         ...,
         [0.6257, 0.0675, 0.5282,  ..., 0.7105, 0.9557, 0.0862],
         [0.2929, 0.1184, 0.6387,  ..., 0.3446, 0.8795, 0.6993],
         [0.8339, 0.7501, 0.9088,  ..., 0.2130, 0.8987, 0.0851]],

        [[0.7666, 0.4512, 0.9981,  ..., 0.6138, 0.6436, 0.8187],
         [0.7539, 0.7337, 0.9694,  ..., 0.6756, 0.3146, 0.1395],
         [0.8064, 0.2067, 0.7245,  ..., 0.4108, 0.3164, 0.3920],
         ...,
         [0.5652, 0.9251, 0.1290,  ..., 0.4376, 0.6987, 0.1886],
         [0.0172, 0.4912, 0.6059,  ..., 0.2232, 0.3378, 0.2434],
         [0.5091, 0.3650, 0.9672,  ..., 0.0170, 0.9663, 0.4238]],

        [[0.2960, 0.4861, 0.3382,  ..., 0.1405, 0.3409, 0.4777],
         [0.9442, 0.3767, 0.2695,  ..., 0.2183, 0.3146, 0.0566],
         [0.3356, 0.8084, 0.7563,  ..., 0.0123, 0.7801, 0.

## Numpy&Pytorch

In [139]:
array=np.arange(1.0,8.0)
tensor=torch.from_numpy(array)
array,tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [140]:
array.dtype

dtype('float64')

In [141]:
tensor.dtype

torch.float64

In [142]:
torch.arange(1.0,8.0).dtype#defult dtype of torch float32 and numpy is float 64

torch.float32

In [143]:
# changing array and tensor does not effect on each other 

## Reproducbility (trying to take random out of random)
In short how neural network learn:

start with random number --> tensor operation --> update random numbers to try and make them better representations of the  data 
--> again --> again --> again....

In [148]:
#random seed
random_seed=44
torch.manual_seed(random_seed)
A=torch.rand(3,4)
torch.manual_seed(random_seed)
B=torch.rand(3,4)
print(B==A)

tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


In [149]:
torch.cuda.is_available()

False